#!/usr/bin/env python
import argparse

from app.main.Visualizer import Visualizer


def main(config_file, weight):
    vis = Visualizer(config_file, weight=weight)
    vis.kernel_visualize()


if __name__ == "__main__":
    """
    """

    # use argparse to accept command line variables (config.ini)
    parser = argparse.ArgumentParser(description='Test a trained model')
    parser.add_argument('config', metavar='config', type=str, help='Configuration file')
    parser.add_argument('-w', help='Weight', type=str, default=None, required=False)
    args = parser.parse_args()

    main(config_file=args.config, weight=args.w)
